### ISSUE TITLE
RFE: TP Template Implement Rerun Failed Tests to save credits

### ISSUE THREAD

**Issue by rgleason** [rgleason/weatherfax_pi#142]
https://circleci.com/docs/rerun-failed-tests/#introduction

https://circleci.com/docs/rerun-failed-tests/

https://circleci.com/docs/collect-test-data/#ctest-for-c-cxx-tests

**Comment by rgleason** [comment]
macOS Intel Support Deprecation in January 2024 
https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718

https://circleci.com/docs/using-macos/#supported-xcode-versions-silicon

We are using in config.yml

```
    build-macos-wx32:
        macos:
            xcode: "12.5.1"
        resource_class: macos.x86.medium.gen2    <----Recently changed to this resource.
        environment:
        - OCPN_TARGET:  macos
        - CLOUDSMITH_PKG_EXT: pkg
        - DEPLOY_USE_ORB: true
        - WX_VER: 32
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-macos.sh
        - deploy-code
```

I don't believe this is apple silicone based, but is Intel.
